replicaCount: 2
webhookSecret: replace-with-webhookSecret
accessToken: replace-with-accessToken

image:
  repository: ghcr.io/robbell/hi
  pullPolicy: Always
  tag: main

service:
  type: LoadBalancer
  port: 80

