replicaCount: 2
webhookSecret: replace-with-webhookSecret
accessToken: replace-with-accessToken

image:
  repository: robbell/hi
  pullPolicy: Always
  tag: latest

service:
  type: LoadBalancer
  port: 80

