apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: prod-issuer
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - 'new.robbell.io'
    - 'other.robbell.io'
    - 'www.robbell.io'
    secretName: {{ include "chart.fullname" . }}-tls-secret
  rules:
  - host: 'new.robbell.io'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  - host: 'other.robbell.io'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  - host: 'www.robbell.io'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "chart.fullname" . }}
            port:
              number: {{ .Values.service.port }}
