apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "chart.fullname" . }}
  resources:
    requests:
      storage: 1Gi
