name: Build image and deploy chart
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/robbell/hi

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Write kubeconfig to disk
        run: echo "${{ secrets.KUBE_CONFIG }}" >> ./kubeconfig

      - name: Replace Webhook Sercret
        run:  sed -i -e 's/replace-with-webhookSecret/${{ secrets.WEBHOOK_SECRET }}/g' ./chart/values.yaml

      - name: Replace Access Token
        run:  sed -i -e 's/replace-with-accessToken/${{ secrets.ACCESS_TOKEN }}/g' ./chart/values.yaml

      - name: Helm Upgrade
        run: helm upgrade robbell-latest ./chart -i --namespace robbell
        env:
          KUBECONFIG: './kubeconfig'
